System.config({
  "defaultJSExtensions": true,
  "transpiler": "systemjs@0.19.17",
  "babelOptions": {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  "paths": {
    "*": "dist/*",
    "shared": "../shared/src/js/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  "map": {
    "-v": "npm:babel-core@5.8.38",
    "-v-runtime": "npm:babel-runtime@5.8.38",
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.2.0",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.2.0",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.0",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.0",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.0",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.0",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.0",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.0",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.0",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "core-js": "npm:core-js@2.2.1",
    "event-registrar": "npm:event-registrar@0.1.2",
    "fetch": "github:github/fetch@0.10.1",
    "font-awesome": "npm:font-awesome@4.5.0",
    "jquery": "npm:jquery@2.2.2",
    "marked": "npm:marked@0.3.5",
    "rxjs": "npm:rxjs@5.0.0-beta.3",
    "systemjs": "npm:systemjs@0.19.17",
    "systemjs-runtime": "npm:babel-runtime@5.8.38",
    "systemjs@0.19.17": "npm:babel-core@5.8.38",
    "systemjs@0.19.17-runtime": "npm:babel-runtime@5.8.38",
    "text": "github:systemjs/plugin-text@0.0.3",
    "watch-css-media": "npm:watch-css-media@0.1.2",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "github:components/jquery@2.2.1"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.0-beta.1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-binding@1.0.0-beta.1.3.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.0",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.0",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.0",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-framework@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.2.0": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.2.0": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-loader@1.0.0-beta.1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-polyfills@1.0.0-beta.1.1.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-router@1.0.0-beta.1.2.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.2.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@2.2.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:es6-module-loader@0.17.11": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "when": "npm:when@3.7.7"
    },
    "npm:font-awesome@4.5.0": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:rxjs@5.0.0-beta.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:systemjs@0.19.17": {
      "es6-module-loader": "npm:es6-module-loader@0.17.11",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "when": "npm:when@3.7.7"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:watch-css-media@0.1.2": {
      "rxjs-es": "npm:rxjs-es@5.0.0-beta.3"
    },
    "npm:when@3.7.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  },
  "bundles": {
    "app-build": [
      "Constants",
      "app",
      "app.html!github:systemjs/plugin-text@0.0.3",
      "components/anchor",
      "components/anchor.html!github:systemjs/plugin-text@0.0.3",
      "components/header-wrapper",
      "components/header-wrapper.html!github:systemjs/plugin-text@0.0.3",
      "components/markdown",
      "components/markdown-value-converter",
      "components/markdown.html!github:systemjs/plugin-text@0.0.3",
      "components/progress-tracker",
      "components/progress-tracker.html!github:systemjs/plugin-text@0.0.3",
      "components/scroll-keeper",
      "components/sticky-header",
      "components/sticky-header.html!github:systemjs/plugin-text@0.0.3",
      "components/swap-page",
      "components/swap-page.html!github:systemjs/plugin-text@0.0.3",
      "main"
    ],
    "aurelia-d3c489b65d": [
      "github:jspm/nodelibs-buffer@0.1.0",
      "github:jspm/nodelibs-buffer@0.1.0/index",
      "github:jspm/nodelibs-process@0.1.2",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:aurelia-animator-css@1.0.0-beta.1.2.0",
      "npm:aurelia-animator-css@1.0.0-beta.1.2.0/aurelia-animator-css",
      "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "npm:aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0/aurelia-bootstrapper",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0/aurelia-dependency-injection",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0/aurelia-event-aggregator",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.0",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.0/aurelia-fetch-client",
      "npm:aurelia-framework@1.0.0-beta.1.2.0",
      "npm:aurelia-framework@1.0.0-beta.1.2.0/aurelia-framework",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.0",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.0/aurelia-history-browser",
      "npm:aurelia-history@1.0.0-beta.1.2.0",
      "npm:aurelia-history@1.0.0-beta.1.2.0/aurelia-history",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.0",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.0/aurelia-loader-default",
      "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "npm:aurelia-loader@1.0.0-beta.1.2.0/aurelia-loader",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.0",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.0/aurelia-logging-console",
      "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "npm:aurelia-logging@1.0.0-beta.1.2.0/aurelia-logging",
      "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "npm:aurelia-metadata@1.0.0-beta.1.2.0/aurelia-metadata",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.0",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.0/aurelia-pal-browser",
      "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "npm:aurelia-pal@1.0.0-beta.1.2.0/aurelia-pal",
      "npm:aurelia-path@1.0.0-beta.1.2.0",
      "npm:aurelia-path@1.0.0-beta.1.2.0/aurelia-path",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.0",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.0/aurelia-polyfills",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0/aurelia-route-recognizer",
      "npm:aurelia-router@1.0.0-beta.1.2.0",
      "npm:aurelia-router@1.0.0-beta.1.2.0/aurelia-router",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.0/aurelia-task-queue",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.0",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.0/aurelia-templating-binding",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/abstract-repeater",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/analyze-view-factory",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/array-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/aurelia-templating-resources",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/binding-mode-behaviors",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/binding-signaler",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/compile-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/compose",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/css-resource",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/debounce-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/dynamic-element",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/focus",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/hide",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/html-sanitizer",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/if",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/map-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/null-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/number-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/repeat",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/repeat-strategy-locator",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/repeat-utilities",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/replaceable",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/sanitize-html",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/set-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/show",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/signal-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/throttle-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/update-trigger-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/view-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/with",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/aurelia-templating-router",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/route-href",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/route-loader",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/router-view",
      "npm:aurelia-templating@1.0.0-beta.1.2.0",
      "npm:aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating",
      "npm:base64-js@0.0.8",
      "npm:base64-js@0.0.8/lib/b64",
      "npm:buffer@3.6.0",
      "npm:buffer@3.6.0/index",
      "npm:event-registrar@0.1.2",
      "npm:event-registrar@0.1.2/dist/event-registrar",
      "npm:event-registrar@0.1.2/index",
      "npm:ieee754@1.1.6",
      "npm:ieee754@1.1.6/index",
      "npm:isarray@1.0.0",
      "npm:isarray@1.0.0/index",
      "npm:marked@0.3.5",
      "npm:marked@0.3.5/lib/marked",
      "npm:process@0.11.2",
      "npm:process@0.11.2/browser",
      "npm:rxjs@5.0.0-beta.3",
      "npm:rxjs@5.0.0-beta.3/InnerSubscriber",
      "npm:rxjs@5.0.0-beta.3/Notification",
      "npm:rxjs@5.0.0-beta.3/Observable",
      "npm:rxjs@5.0.0-beta.3/Observer",
      "npm:rxjs@5.0.0-beta.3/Operator",
      "npm:rxjs@5.0.0-beta.3/OuterSubscriber",
      "npm:rxjs@5.0.0-beta.3/Rx",
      "npm:rxjs@5.0.0-beta.3/Subject",
      "npm:rxjs@5.0.0-beta.3/Subscriber",
      "npm:rxjs@5.0.0-beta.3/Subscription",
      "npm:rxjs@5.0.0-beta.3/add/observable/bindCallback",
      "npm:rxjs@5.0.0-beta.3/add/observable/bindNodeCallback",
      "npm:rxjs@5.0.0-beta.3/add/observable/combineLatest",
      "npm:rxjs@5.0.0-beta.3/add/observable/concat",
      "npm:rxjs@5.0.0-beta.3/add/observable/defer",
      "npm:rxjs@5.0.0-beta.3/add/observable/empty",
      "npm:rxjs@5.0.0-beta.3/add/observable/forkJoin",
      "npm:rxjs@5.0.0-beta.3/add/observable/from",
      "npm:rxjs@5.0.0-beta.3/add/observable/fromArray",
      "npm:rxjs@5.0.0-beta.3/add/observable/fromEvent",
      "npm:rxjs@5.0.0-beta.3/add/observable/fromEventPattern",
      "npm:rxjs@5.0.0-beta.3/add/observable/fromPromise",
      "npm:rxjs@5.0.0-beta.3/add/observable/interval",
      "npm:rxjs@5.0.0-beta.3/add/observable/merge",
      "npm:rxjs@5.0.0-beta.3/add/observable/never",
      "npm:rxjs@5.0.0-beta.3/add/observable/of",
      "npm:rxjs@5.0.0-beta.3/add/observable/race",
      "npm:rxjs@5.0.0-beta.3/add/observable/range",
      "npm:rxjs@5.0.0-beta.3/add/observable/throw",
      "npm:rxjs@5.0.0-beta.3/add/observable/timer",
      "npm:rxjs@5.0.0-beta.3/add/observable/zip",
      "npm:rxjs@5.0.0-beta.3/add/operator/buffer",
      "npm:rxjs@5.0.0-beta.3/add/operator/bufferCount",
      "npm:rxjs@5.0.0-beta.3/add/operator/bufferTime",
      "npm:rxjs@5.0.0-beta.3/add/operator/bufferToggle",
      "npm:rxjs@5.0.0-beta.3/add/operator/bufferWhen",
      "npm:rxjs@5.0.0-beta.3/add/operator/cache",
      "npm:rxjs@5.0.0-beta.3/add/operator/catch",
      "npm:rxjs@5.0.0-beta.3/add/operator/combineAll",
      "npm:rxjs@5.0.0-beta.3/add/operator/combineLatest",
      "npm:rxjs@5.0.0-beta.3/add/operator/concat",
      "npm:rxjs@5.0.0-beta.3/add/operator/concatAll",
      "npm:rxjs@5.0.0-beta.3/add/operator/concatMap",
      "npm:rxjs@5.0.0-beta.3/add/operator/concatMapTo",
      "npm:rxjs@5.0.0-beta.3/add/operator/count",
      "npm:rxjs@5.0.0-beta.3/add/operator/debounce",
      "npm:rxjs@5.0.0-beta.3/add/operator/debounceTime",
      "npm:rxjs@5.0.0-beta.3/add/operator/defaultIfEmpty",
      "npm:rxjs@5.0.0-beta.3/add/operator/delay",
      "npm:rxjs@5.0.0-beta.3/add/operator/delayWhen",
      "npm:rxjs@5.0.0-beta.3/add/operator/dematerialize",
      "npm:rxjs@5.0.0-beta.3/add/operator/distinctUntilChanged",
      "npm:rxjs@5.0.0-beta.3/add/operator/do",
      "npm:rxjs@5.0.0-beta.3/add/operator/every",
      "npm:rxjs@5.0.0-beta.3/add/operator/expand",
      "npm:rxjs@5.0.0-beta.3/add/operator/filter",
      "npm:rxjs@5.0.0-beta.3/add/operator/finally",
      "npm:rxjs@5.0.0-beta.3/add/operator/first",
      "npm:rxjs@5.0.0-beta.3/add/operator/groupBy",
      "npm:rxjs@5.0.0-beta.3/add/operator/ignoreElements",
      "npm:rxjs@5.0.0-beta.3/add/operator/inspect",
      "npm:rxjs@5.0.0-beta.3/add/operator/inspectTime",
      "npm:rxjs@5.0.0-beta.3/add/operator/last",
      "npm:rxjs@5.0.0-beta.3/add/operator/let",
      "npm:rxjs@5.0.0-beta.3/add/operator/map",
      "npm:rxjs@5.0.0-beta.3/add/operator/mapTo",
      "npm:rxjs@5.0.0-beta.3/add/operator/materialize",
      "npm:rxjs@5.0.0-beta.3/add/operator/merge",
      "npm:rxjs@5.0.0-beta.3/add/operator/mergeAll",
      "npm:rxjs@5.0.0-beta.3/add/operator/mergeMap",
      "npm:rxjs@5.0.0-beta.3/add/operator/mergeMapTo",
      "npm:rxjs@5.0.0-beta.3/add/operator/multicast",
      "npm:rxjs@5.0.0-beta.3/add/operator/observeOn",
      "npm:rxjs@5.0.0-beta.3/add/operator/partition",
      "npm:rxjs@5.0.0-beta.3/add/operator/pluck",
      "npm:rxjs@5.0.0-beta.3/add/operator/publish",
      "npm:rxjs@5.0.0-beta.3/add/operator/publishBehavior",
      "npm:rxjs@5.0.0-beta.3/add/operator/publishLast",
      "npm:rxjs@5.0.0-beta.3/add/operator/publishReplay",
      "npm:rxjs@5.0.0-beta.3/add/operator/race",
      "npm:rxjs@5.0.0-beta.3/add/operator/reduce",
      "npm:rxjs@5.0.0-beta.3/add/operator/repeat",
      "npm:rxjs@5.0.0-beta.3/add/operator/retry",
      "npm:rxjs@5.0.0-beta.3/add/operator/retryWhen",
      "npm:rxjs@5.0.0-beta.3/add/operator/sample",
      "npm:rxjs@5.0.0-beta.3/add/operator/sampleTime",
      "npm:rxjs@5.0.0-beta.3/add/operator/scan",
      "npm:rxjs@5.0.0-beta.3/add/operator/share",
      "npm:rxjs@5.0.0-beta.3/add/operator/single",
      "npm:rxjs@5.0.0-beta.3/add/operator/skip",
      "npm:rxjs@5.0.0-beta.3/add/operator/skipUntil",
      "npm:rxjs@5.0.0-beta.3/add/operator/skipWhile",
      "npm:rxjs@5.0.0-beta.3/add/operator/startWith",
      "npm:rxjs@5.0.0-beta.3/add/operator/subscribeOn",
      "npm:rxjs@5.0.0-beta.3/add/operator/switch",
      "npm:rxjs@5.0.0-beta.3/add/operator/switchMap",
      "npm:rxjs@5.0.0-beta.3/add/operator/switchMapTo",
      "npm:rxjs@5.0.0-beta.3/add/operator/take",
      "npm:rxjs@5.0.0-beta.3/add/operator/takeLast",
      "npm:rxjs@5.0.0-beta.3/add/operator/takeUntil",
      "npm:rxjs@5.0.0-beta.3/add/operator/takeWhile",
      "npm:rxjs@5.0.0-beta.3/add/operator/throttle",
      "npm:rxjs@5.0.0-beta.3/add/operator/throttleTime",
      "npm:rxjs@5.0.0-beta.3/add/operator/timeout",
      "npm:rxjs@5.0.0-beta.3/add/operator/timeoutWith",
      "npm:rxjs@5.0.0-beta.3/add/operator/toArray",
      "npm:rxjs@5.0.0-beta.3/add/operator/toPromise",
      "npm:rxjs@5.0.0-beta.3/add/operator/window",
      "npm:rxjs@5.0.0-beta.3/add/operator/windowCount",
      "npm:rxjs@5.0.0-beta.3/add/operator/windowTime",
      "npm:rxjs@5.0.0-beta.3/add/operator/windowToggle",
      "npm:rxjs@5.0.0-beta.3/add/operator/windowWhen",
      "npm:rxjs@5.0.0-beta.3/add/operator/withLatestFrom",
      "npm:rxjs@5.0.0-beta.3/add/operator/zip",
      "npm:rxjs@5.0.0-beta.3/add/operator/zipAll",
      "npm:rxjs@5.0.0-beta.3/observable/ArrayLikeObservable",
      "npm:rxjs@5.0.0-beta.3/observable/ArrayObservable",
      "npm:rxjs@5.0.0-beta.3/observable/BoundCallbackObservable",
      "npm:rxjs@5.0.0-beta.3/observable/BoundNodeCallbackObservable",
      "npm:rxjs@5.0.0-beta.3/observable/ConnectableObservable",
      "npm:rxjs@5.0.0-beta.3/observable/DeferObservable",
      "npm:rxjs@5.0.0-beta.3/observable/EmptyObservable",
      "npm:rxjs@5.0.0-beta.3/observable/ErrorObservable",
      "npm:rxjs@5.0.0-beta.3/observable/ForkJoinObservable",
      "npm:rxjs@5.0.0-beta.3/observable/FromEventObservable",
      "npm:rxjs@5.0.0-beta.3/observable/FromEventPatternObservable",
      "npm:rxjs@5.0.0-beta.3/observable/FromObservable",
      "npm:rxjs@5.0.0-beta.3/observable/IntervalObservable",
      "npm:rxjs@5.0.0-beta.3/observable/IteratorObservable",
      "npm:rxjs@5.0.0-beta.3/observable/NeverObservable",
      "npm:rxjs@5.0.0-beta.3/observable/PromiseObservable",
      "npm:rxjs@5.0.0-beta.3/observable/RangeObservable",
      "npm:rxjs@5.0.0-beta.3/observable/ScalarObservable",
      "npm:rxjs@5.0.0-beta.3/observable/SubscribeOnObservable",
      "npm:rxjs@5.0.0-beta.3/observable/TimerObservable",
      "npm:rxjs@5.0.0-beta.3/operator/buffer",
      "npm:rxjs@5.0.0-beta.3/operator/bufferCount",
      "npm:rxjs@5.0.0-beta.3/operator/bufferTime",
      "npm:rxjs@5.0.0-beta.3/operator/bufferToggle",
      "npm:rxjs@5.0.0-beta.3/operator/bufferWhen",
      "npm:rxjs@5.0.0-beta.3/operator/cache",
      "npm:rxjs@5.0.0-beta.3/operator/catch",
      "npm:rxjs@5.0.0-beta.3/operator/combineAll",
      "npm:rxjs@5.0.0-beta.3/operator/combineLatest",
      "npm:rxjs@5.0.0-beta.3/operator/concat",
      "npm:rxjs@5.0.0-beta.3/operator/concatAll",
      "npm:rxjs@5.0.0-beta.3/operator/concatMap",
      "npm:rxjs@5.0.0-beta.3/operator/concatMapTo",
      "npm:rxjs@5.0.0-beta.3/operator/count",
      "npm:rxjs@5.0.0-beta.3/operator/debounce",
      "npm:rxjs@5.0.0-beta.3/operator/debounceTime",
      "npm:rxjs@5.0.0-beta.3/operator/defaultIfEmpty",
      "npm:rxjs@5.0.0-beta.3/operator/delay",
      "npm:rxjs@5.0.0-beta.3/operator/delayWhen",
      "npm:rxjs@5.0.0-beta.3/operator/dematerialize",
      "npm:rxjs@5.0.0-beta.3/operator/distinctUntilChanged",
      "npm:rxjs@5.0.0-beta.3/operator/do",
      "npm:rxjs@5.0.0-beta.3/operator/every",
      "npm:rxjs@5.0.0-beta.3/operator/expand",
      "npm:rxjs@5.0.0-beta.3/operator/filter",
      "npm:rxjs@5.0.0-beta.3/operator/finally",
      "npm:rxjs@5.0.0-beta.3/operator/first",
      "npm:rxjs@5.0.0-beta.3/operator/groupBy",
      "npm:rxjs@5.0.0-beta.3/operator/ignoreElements",
      "npm:rxjs@5.0.0-beta.3/operator/inspect",
      "npm:rxjs@5.0.0-beta.3/operator/inspectTime",
      "npm:rxjs@5.0.0-beta.3/operator/last",
      "npm:rxjs@5.0.0-beta.3/operator/let",
      "npm:rxjs@5.0.0-beta.3/operator/map",
      "npm:rxjs@5.0.0-beta.3/operator/mapTo",
      "npm:rxjs@5.0.0-beta.3/operator/materialize",
      "npm:rxjs@5.0.0-beta.3/operator/merge",
      "npm:rxjs@5.0.0-beta.3/operator/mergeAll",
      "npm:rxjs@5.0.0-beta.3/operator/mergeMap",
      "npm:rxjs@5.0.0-beta.3/operator/mergeMapTo",
      "npm:rxjs@5.0.0-beta.3/operator/multicast",
      "npm:rxjs@5.0.0-beta.3/operator/observeOn",
      "npm:rxjs@5.0.0-beta.3/operator/partition",
      "npm:rxjs@5.0.0-beta.3/operator/pluck",
      "npm:rxjs@5.0.0-beta.3/operator/publish",
      "npm:rxjs@5.0.0-beta.3/operator/publishBehavior",
      "npm:rxjs@5.0.0-beta.3/operator/publishLast",
      "npm:rxjs@5.0.0-beta.3/operator/publishReplay",
      "npm:rxjs@5.0.0-beta.3/operator/race",
      "npm:rxjs@5.0.0-beta.3/operator/reduce",
      "npm:rxjs@5.0.0-beta.3/operator/repeat",
      "npm:rxjs@5.0.0-beta.3/operator/retry",
      "npm:rxjs@5.0.0-beta.3/operator/retryWhen",
      "npm:rxjs@5.0.0-beta.3/operator/sample",
      "npm:rxjs@5.0.0-beta.3/operator/sampleTime",
      "npm:rxjs@5.0.0-beta.3/operator/scan",
      "npm:rxjs@5.0.0-beta.3/operator/share",
      "npm:rxjs@5.0.0-beta.3/operator/single",
      "npm:rxjs@5.0.0-beta.3/operator/skip",
      "npm:rxjs@5.0.0-beta.3/operator/skipUntil",
      "npm:rxjs@5.0.0-beta.3/operator/skipWhile",
      "npm:rxjs@5.0.0-beta.3/operator/startWith",
      "npm:rxjs@5.0.0-beta.3/operator/subscribeOn",
      "npm:rxjs@5.0.0-beta.3/operator/switch",
      "npm:rxjs@5.0.0-beta.3/operator/switchMap",
      "npm:rxjs@5.0.0-beta.3/operator/switchMapTo",
      "npm:rxjs@5.0.0-beta.3/operator/take",
      "npm:rxjs@5.0.0-beta.3/operator/takeLast",
      "npm:rxjs@5.0.0-beta.3/operator/takeUntil",
      "npm:rxjs@5.0.0-beta.3/operator/takeWhile",
      "npm:rxjs@5.0.0-beta.3/operator/throttle",
      "npm:rxjs@5.0.0-beta.3/operator/throttleTime",
      "npm:rxjs@5.0.0-beta.3/operator/timeout",
      "npm:rxjs@5.0.0-beta.3/operator/timeoutWith",
      "npm:rxjs@5.0.0-beta.3/operator/toArray",
      "npm:rxjs@5.0.0-beta.3/operator/toPromise",
      "npm:rxjs@5.0.0-beta.3/operator/window",
      "npm:rxjs@5.0.0-beta.3/operator/windowCount",
      "npm:rxjs@5.0.0-beta.3/operator/windowTime",
      "npm:rxjs@5.0.0-beta.3/operator/windowToggle",
      "npm:rxjs@5.0.0-beta.3/operator/windowWhen",
      "npm:rxjs@5.0.0-beta.3/operator/withLatestFrom",
      "npm:rxjs@5.0.0-beta.3/operator/zip",
      "npm:rxjs@5.0.0-beta.3/operator/zipAll",
      "npm:rxjs@5.0.0-beta.3/scheduler/AsapAction",
      "npm:rxjs@5.0.0-beta.3/scheduler/AsapScheduler",
      "npm:rxjs@5.0.0-beta.3/scheduler/AsyncScheduler",
      "npm:rxjs@5.0.0-beta.3/scheduler/FutureAction",
      "npm:rxjs@5.0.0-beta.3/scheduler/QueueAction",
      "npm:rxjs@5.0.0-beta.3/scheduler/QueueScheduler",
      "npm:rxjs@5.0.0-beta.3/scheduler/asap",
      "npm:rxjs@5.0.0-beta.3/scheduler/async",
      "npm:rxjs@5.0.0-beta.3/scheduler/queue",
      "npm:rxjs@5.0.0-beta.3/subject/AsyncSubject",
      "npm:rxjs@5.0.0-beta.3/subject/BehaviorSubject",
      "npm:rxjs@5.0.0-beta.3/subject/ReplaySubject",
      "npm:rxjs@5.0.0-beta.3/subject/SubjectSubscription",
      "npm:rxjs@5.0.0-beta.3/symbol/iterator",
      "npm:rxjs@5.0.0-beta.3/symbol/observable",
      "npm:rxjs@5.0.0-beta.3/symbol/rxSubscriber",
      "npm:rxjs@5.0.0-beta.3/util/ArgumentOutOfRangeError",
      "npm:rxjs@5.0.0-beta.3/util/EmptyError",
      "npm:rxjs@5.0.0-beta.3/util/FastMap",
      "npm:rxjs@5.0.0-beta.3/util/Immediate",
      "npm:rxjs@5.0.0-beta.3/util/Map",
      "npm:rxjs@5.0.0-beta.3/util/MapPolyfill",
      "npm:rxjs@5.0.0-beta.3/util/ObjectUnsubscribedError",
      "npm:rxjs@5.0.0-beta.3/util/errorObject",
      "npm:rxjs@5.0.0-beta.3/util/isArray",
      "npm:rxjs@5.0.0-beta.3/util/isDate",
      "npm:rxjs@5.0.0-beta.3/util/isFunction",
      "npm:rxjs@5.0.0-beta.3/util/isNumeric",
      "npm:rxjs@5.0.0-beta.3/util/isObject",
      "npm:rxjs@5.0.0-beta.3/util/isPromise",
      "npm:rxjs@5.0.0-beta.3/util/isScheduler",
      "npm:rxjs@5.0.0-beta.3/util/noop",
      "npm:rxjs@5.0.0-beta.3/util/not",
      "npm:rxjs@5.0.0-beta.3/util/root",
      "npm:rxjs@5.0.0-beta.3/util/subscribeToResult",
      "npm:rxjs@5.0.0-beta.3/util/throwError",
      "npm:rxjs@5.0.0-beta.3/util/toSubscriber",
      "npm:rxjs@5.0.0-beta.3/util/tryCatch",
      "npm:watch-css-media@0.1.2",
      "npm:watch-css-media@0.1.2/dist/watch-css-media",
      "npm:watch-css-media@0.1.2/index",
      "shared/constants",
      "shared/event-registrar",
      "shared/style-constants",
      "shared/url-constants",
      "shared/utils"
    ]
  }
})